spring:
  application:
    name: Spacemarine-Service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paint}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driverClassName: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  test:
    ignore-configuration-validation:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      continue-on-error: true
server:
  port: 8000
