spring:
  application:
    name: Spacemarine-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/paint
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  test:
    ignore-configuration-validation:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080
