spring:
  application:
    name: Spacemarine-Service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  test:
    ignore-configuration-validation:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      continue-on-error: true
server:
  port: 8080
